# Generated by Django 3.0.5 on 2023-10-23 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0003_remove_blooddonate_bloodgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='blooddonate',
            name='bloodgroup',
            field=models.CharField(default='A+', max_length=10),
        ),
    ]
