# Generated by Django 3.0.5 on 2023-10-23 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0004_blooddonate_bloodgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blooddonate',
            name='bloodgroup',
            field=models.CharField(max_length=10),
        ),
    ]
