# Generated by Django 3.0.5 on 2023-10-22 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_auto_20231021_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='bloodgroup',
            field=models.CharField(default='O', max_length=10),
            preserve_default=False,
        ),
    ]
