# Generated by Django 3.0.5 on 2023-10-21 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0005_bloodrequest_doctorname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bloodrequest',
            old_name='doctorname',
            new_name='doctor_name',
        ),
    ]
